name: api-load-test

stages:
  - duration: 10s
    target_vus: 100
  - duration: 20s
    target_vus: 500
  - duration: 10s
    target_vus: 0

endpoints:
  - url: https://httpbin.org/get
    method: GET
    weight: 70

  - url: https://httpbin.org/post
    method: POST
    weight: 30
    body: '{"id":"{{uuid}}","ts":"{{timestamp}}"}'
    expected_status: 200