// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/suddpanzer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SuddpanzerAgent_RunScenario_FullMethodName = "/suddpanzer.SuddpanzerAgent/RunScenario"
)

// SuddpanzerAgentClient is the client API for SuddpanzerAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SuddpanzerAgentClient interface {
	RunScenario(ctx context.Context, in *WorkSpec, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsSnapshot], error)
}

type suddpanzerAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewSuddpanzerAgentClient(cc grpc.ClientConnInterface) SuddpanzerAgentClient {
	return &suddpanzerAgentClient{cc}
}

func (c *suddpanzerAgentClient) RunScenario(ctx context.Context, in *WorkSpec, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricsSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SuddpanzerAgent_ServiceDesc.Streams[0], SuddpanzerAgent_RunScenario_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkSpec, MetricsSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SuddpanzerAgent_RunScenarioClient = grpc.ServerStreamingClient[MetricsSnapshot]

// SuddpanzerAgentServer is the server API for SuddpanzerAgent service.
// All implementations must embed UnimplementedSuddpanzerAgentServer
// for forward compatibility.
type SuddpanzerAgentServer interface {
	RunScenario(*WorkSpec, grpc.ServerStreamingServer[MetricsSnapshot]) error
	mustEmbedUnimplementedSuddpanzerAgentServer()
}

// UnimplementedSuddpanzerAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSuddpanzerAgentServer struct{}

func (UnimplementedSuddpanzerAgentServer) RunScenario(*WorkSpec, grpc.ServerStreamingServer[MetricsSnapshot]) error {
	return status.Error(codes.Unimplemented, "method RunScenario not implemented")
}
func (UnimplementedSuddpanzerAgentServer) mustEmbedUnimplementedSuddpanzerAgentServer() {}
func (UnimplementedSuddpanzerAgentServer) testEmbeddedByValue()                         {}

// UnsafeSuddpanzerAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SuddpanzerAgentServer will
// result in compilation errors.
type UnsafeSuddpanzerAgentServer interface {
	mustEmbedUnimplementedSuddpanzerAgentServer()
}

func RegisterSuddpanzerAgentServer(s grpc.ServiceRegistrar, srv SuddpanzerAgentServer) {
	// If the following call panics, it indicates UnimplementedSuddpanzerAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SuddpanzerAgent_ServiceDesc, srv)
}

func _SuddpanzerAgent_RunScenario_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorkSpec)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SuddpanzerAgentServer).RunScenario(m, &grpc.GenericServerStream[WorkSpec, MetricsSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SuddpanzerAgent_RunScenarioServer = grpc.ServerStreamingServer[MetricsSnapshot]

// SuddpanzerAgent_ServiceDesc is the grpc.ServiceDesc for SuddpanzerAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SuddpanzerAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "suddpanzer.SuddpanzerAgent",
	HandlerType: (*SuddpanzerAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunScenario",
			Handler:       _SuddpanzerAgent_RunScenario_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/suddpanzer.proto",
}
